language: cpp

install: 
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo apt-get update
  - sudo apt-get install libsdl2-dev
  - sudo apt-get install -y gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j3